name: Reusable Nightly Build (from Develop branch)

on:
   workflow_call:
# In the reusable workflow,
      secrets:
# use the inputs and secrets keywords
# to define inputs or secrets that will be
# passed from a caller workflow.
         ARTIFACTORY_HOSTNAME:
            required: true
# In the reusable workflow,
         ARTIFACTORY_SNAPSHOT_REPO:
            required: true
         ARTIFACTORY_RELEASE_REPO:
            required: true
         ARTIFACTORY_USERNAME:
            required: true
         ARTIFACTORY_TOKEN:


            required: true
jobs:
   reusable-build-deploy:
      runs-on: ubuntu-latest
# reference the input or secret that you defined in the "on" key in the previous step.
# If the secrets are inherited using "secrets: inherit",
# you can reference them even if they are not defined in the on key.
      steps:
      -  name: Checkout project
         uses: actions/checkout@v2
      -  name: Cache local Maven repository
         uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-maven-
      -  name: Set up JDK 11
         uses: actions/setup-java@v2
         with:
            java-version: '11'
            distribution: temurin
      -  name: Setup Maven settings.xml
         uses: whelk-io/maven-settings-xml-action@v18
         with:
            servers: |
               [
                 {
                   "id": "qiot-central",
                   "username": "${env.ARTIFACTORY_USERNAME_REF}",
                   "password": "${env.ARTIFACTORY_TOKEN_REF}"
                 },
                 {
                   "id": "qiot-snapshots",
                   "username": "${env.ARTIFACTORY_USERNAME_REF}",
                   "password": "${env.ARTIFACTORY_TOKEN_REF}"
                 }
               ]
      -  name: Build with Maven
         env:
            ARTIFACTORY_HOSTNAME: ${{ secrets.ARTIFACTORY_HOSTNAME }}
            ARTIFACTORY_SNAPSHOT_REPO: ${{ secrets.ARTIFACTORY_SNAPSHOT_REPO }}
            ARTIFACTORY_RELEASE_REPO: ${{ secrets.ARTIFACTORY_RELEASE_REPO }}
            ARTIFACTORY_USERNAME_REF: ${{ secrets.ARTIFACTORY_USERNAME }}
            ARTIFACTORY_TOKEN_REF: ${{ secrets.ARTIFACTORY_TOKEN }}
# BUILD_ENV: 'github-actions'
         run: ./mvnw -B deploy -DARTIFACTORY_HOSTNAME=${{ secrets.ARTIFACTORY_HOSTNAME }} -DARTIFACTORY_SNAPSHOT_REPO=${{ secrets.ARTIFACTORY_SNAPSHOT_REPO }} -DARTIFACTORY_RELEASE_REPO=${{ secrets.ARTIFACTORY_RELEASE_REPO }} -DARTIFACTORY_USERNAME_REF=${{ secrets.ARTIFACTORY_USERNAME }} -DARTIFACTORY_TOKEN_REF=${{ secrets.ARTIFACTORY_TOKEN }}
         